// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFmZxxHkGWEJJ0HjCM-5gM1FX8Kg-pR9o',
    appId: '1:218283000075:web:74f711d0b42356b6e6620e',
    messagingSenderId: '218283000075',
    projectId: 'fir-app-31765',
    authDomain: 'fir-app-31765.firebaseapp.com',
    storageBucket: 'fir-app-31765.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8SNl2Ky6siQ_busbgWfGmecPiuwNSa6s',
    appId: '1:218283000075:android:f1d980d5c1fa6a4de6620e',
    messagingSenderId: '218283000075',
    projectId: 'fir-app-31765',
    storageBucket: 'fir-app-31765.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOYAEmtpIR8Wdx9HJsCijbXHY8s0qOCcE',
    appId: '1:218283000075:ios:80b9b33bf15145ebe6620e',
    messagingSenderId: '218283000075',
    projectId: 'fir-app-31765',
    storageBucket: 'fir-app-31765.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOYAEmtpIR8Wdx9HJsCijbXHY8s0qOCcE',
    appId: '1:218283000075:ios:80b9b33bf15145ebe6620e',
    messagingSenderId: '218283000075',
    projectId: 'fir-app-31765',
    storageBucket: 'fir-app-31765.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFmZxxHkGWEJJ0HjCM-5gM1FX8Kg-pR9o',
    appId: '1:218283000075:web:fcc9e7b573e1ce5de6620e',
    messagingSenderId: '218283000075',
    projectId: 'fir-app-31765',
    authDomain: 'fir-app-31765.firebaseapp.com',
    storageBucket: 'fir-app-31765.firebasestorage.app',
  );
}
